config/routes.rb
IitbQuizee::Application.routes.draw do
  

  devise_for :users
   devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
 
 
  resources :users
  
  resources :folders do
    member do
      get 'move'
      get 'tree_structure'
    end

    collection do
      get 'folder_tree'
    end
  end
  
  root :to => "home#index" 
  resources :documents do 
    member do
      get 'download'
    end
  end 
  get "home/dashboard"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :documents ,:dependent => :destroy  
  
  has_many :folders ,:dependent => :destroy
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:admin,:super_admin,:name

  
  # If super_admin field is enable then current_user is authorized 
  def is_admin?
    self.admin
  end
  
  def is_super_admin?
    self.super_admin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 load_and_authorize_resource

	def index
		@users = User.all
		@user = User.new if current_user.is_admin? || current_user.is_super_admin?
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		respond_to do |format|
		  if @user.save
		  
			  flash[:notice] = "Successfully created User."
			  format.html{redirect_to(users_path,:notice=>"Successfully created User.")}
			  format.js
		  else
        format.html{render :action => 'new'}
			  format.js{render :template => 'layouts/error',:locals=>{:object=>@user}}
		  end
		end
	end

	def edit
		if current_user.is_admin? || current_user.is_super_admin? 
			@user = User.find(params[:id])
		else
			@user = current_user
		end
	end

	def update
		if current_user.admin?
			@user = User.find(params[:id])
		else
			@user = current_user
		end
    params[:user].delete(:email) if params[:user][:email] != @user.email
		params[:user].delete(:password) if params[:user][:password].blank?
		params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
		respond_to do |format|
		if @user.update_attributes(params[:user])
			flash[:notice] = "Successfully updated User."
			format.html{redirect_to(users_path,:notice=>"Successfully updated User.")}
			format.js
		else
			format.html{render :action => 'edit'}
			format.js{render :template => 'layouts/error',:locals=>{:object=>@user}}
		end
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:notice] = "Successfully deleted User."
			redirect_to users_path
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="modal" style="display:none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3 class="modal-title">Add User</h3>
  </div>
  <div class="modal-body">
    <%= form_for(user,:remote=>true, :html=>{:class=>'data-form'}) do |f| %>
 
        <div id="error_explanation">
         
        </div>

     <fieldset>
		  <div class="clearfix">
			  <%= f.label :email %>
			  <div class="input">
			  	<%= f.email_field :email %>
			  </div>
		  </div>
      <div class="clearfix">
			  <%= f.label :name %>
			  <div class="input">
			  	<%= f.text_field :name %>
			  </div>
		  </div>
     <div class="clearfix">
			  <%= f.label :password %>
			  <div class="input">
			  	<%= f.password_field :password %>
			  </div>
		  </div>
    <div class="clearfix">
			  <%= f.label :password %>
			  <div class="input">
			  	<%= f.password_field :password_confirmation %>
			  </div>
		  </div>
    <div class="clearfix">
	    <%= f.label :admin %><div class="input"><%= f.check_box :admin %>		  </div>
	  </div>  
    
  </fieldset>
  </div>

  <div class="modal-footer">
    <%= f.submit "Save Changes", :class => "btn btn-primary" %>
    <a href="#" class="btn close-modal">Close</a>
  </div>
</div>
<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td><%= user.email%> </td>
  <td><%= user.name%> </td>
  <td><%=link_to image_tag("edit_10.png") ,edit_user_path(user),:class=>"editUser"%>
  <%=link_to image_tag("delete_10.png") ,user,:method=>:delete,:confirm=>"Are You sure you want to delete?" %> </td>
</tr>

app/views/users/create.js.erb
$(".modal").modal('hide');

app/views/users/edit.html.erb
<h2>Edit <%= @user.email.to_s.humanize %></h2>

<%= form_for(@user, :html => { :method => :put,:class=>'data-form'} ) do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p><%= f.label :email %><br />
      <%= f.text_field :email %></p>

    <p><%= f.label :name %><br />
      <%= f.text_field :name %></p>

    <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p>

    <p><%= f.label :admin %><br />
      <%= f.check_box :admin %></p>

    <p><%= f.submit "Update" %></p>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%#= link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/users/edit.js.erb
<%= render :partial=>'form',:locals=>{:user=>@user}%>

app/views/users/index.html.erb
<div class="add-asset" style="float:right">

  <%= link_to 'Add User',"#",:class=>"btn addUser" %>
</div>
<div class="listing">
  <table class="table-striped">
    <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th width="40"></th>
    </tr>
    </thead>
    <tbody>
   <%= render @users %>
   </tbody>
  </table>
</div>
<div id="editUserModal" style="display:none">
</div>
<% if current_user.is_admin? || current_user.is_super_admin? %>
  <%= render :partial=>'form',:locals=>{:user=>@user} %>
<% end %>

app/views/users/new.html.erb
<h2>Add User</h2>

<%= form_for(@user, :html=>{:class=>'data-form'}) do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.label :email %><br />
    <%= f.text_field :email %></p>

  <p><%= f.label :name %><br />
    <%= f.text_field :name %></p>

  <p><%= f.label :password %><br />
    <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %></p>
    <p><%= f.label :admin %><br />
      <%= f.check_box :admin %></p>
  <p><%= f.submit "Sign up" %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.js.erb
$("#<%= dom_id(@user) %>").html("<%= escape_javascript( render :partial=>@user)%>");
$(".modal").hide();