config/routes.rb
IitbQuizee::Application.routes.draw do
  

  devise_for :users
   devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
 
 
  resources :users
  
  resources :folders do
    member do
      get 'move'
      get 'tree_structure'
    end

    collection do
      get 'folder_tree'
    end
  end
  
  root :to => "home#index" 
  resources :documents do 
    member do
      get 'download'
    end
  end 
  get "home/dashboard"

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  mount_uploader  :asset, DocumentUploader
  validates_presence_of   :name
  validates_uniqueness_of :name,:message => "Name already taken"
  validates_format_of :name ,:with =>  /[A-Z|a-z]/ ,:allow_blank => true ,:allow_nil => true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  authorize_resource
  
  def index
    
    folders   =  Folder.where("parent_id is ?", nil).order("folders.id").includes(:user)
    documents =  Document.where("folder_id IS ?",nil).includes(:user)
    @folders = Folder.where("parent_id is ?",nil)
    @assets = folders + documents
    @parent_id = nil
  end
  
  def new
    @document =  current_user.documents.new
  end
  
  def create

    @document = current_user.documents.new(params[:document])
    respond_to do |format|
      if @document.save
        format.js
      else
        render :action => :new  
      end
    end
  end
  
  def show
     @document = Document.find(params[:id])
  end
  
  def edit
    @document =  current_user.documents.find(params[:id])
  end
  
  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      redirect_to documents_path
    else
      render :action => :new  
    end
  end
  
  def destroy
    @document = Document.find(params[:id])
    if @document.destroy
      flash[:notice] = "File Deleted"
      redirect_to documents_path
    else
      flash[:notice] = "Something Went Wrong While deleting"
    end
  end
  
  def download
    @document = Document.find(params[:id])
    send_file(@document.asset.file.file)
  end
end

app/views/documents/_asset.html.erb
<tr id="<%=dom_id(asset)%>" class="<%= cycle("odd", "even") %>"> 
  <td>
    <img class="<%= asset.class.name.downcase %>_icon" ></span><%= link_to asset.name,asset,:class => asset.class.name.downcase %> 
  </td>

  <td>
    <%= asset.created_at %>
  </td>
  <td>
    <%= asset.updated_at %>
  </td>
  <!--
  <td>
    <#%#= asset.extension %>
  </td>

  -->
  <td>
    <%= asset.user.name %>
  </td>
</tr>

app/views/documents/_index.html.erb
<% if can? :create,[Folder,Document] %>
    <div class="add-asset" style="float:right">
      <%= link_to 'Add Document',"#",:class=>"btn addDocument" %>
    </div>
    
     <div class="add-asset" style="float:left">
        <%= link_to 'Add Folder',"#",:class=>"btn addFolder" %>
    </div>
  <%end%>
  <br/>
  <br/>
  <table class="table table-striped table-bordered table-condensed" id="table">
    <thead>
      <tr>
        <th> Name </th>
        <th> Uploaded At </th>
        <th> Last Modified At </th>
        <!-- <th> Extension </th> -->
        <th> Uploaded By</th>
      </tr>
    </thead>

    <tbody id="container">
      <%= render :partial => "documents/asset" ,:collection => assets ,:as => :asset %>
    </tbody>
  </table>



  <% if can? :create,[Folder,Document] %>
    <%= render :partial => "folders/new_folder" , :locals => {:folder => Folder.new ,:flash => flash ,:parent_id => parent_id } %>
    <%= render :partial => "documents/new" ,:locals => {:document => Document.new ,:flash => flash,:parent_id => parent_id} %>
  <%end%>

app/views/documents/_new.html.erb
<div class="modal" id="new" style="display:none">
  <div class="modal-header">
    <a class="close" data-dismiss="modal" data-cursor="true">×</a>
      <h2> Attach A Document</h2>
      <div class="alert <%= flash[:type] %>" id="flash-message">
          <%= flash[:message] %> 
      </div>
   </div>
   <div class="modal-body">
    <%= form_for document, :remote => true ,:html => {:multipart => true,:id => "new_document"} do |f| %>
      <p>
        <%= f.text_field :name ,:placeholder => "Name of Document" %>
      </p>
        <%= f.file_field :asset %>
        <%= f.hidden_field :asset_cache %>
        <%= f.hidden_field :folder_id ,:value => parent_id%>
      </p>   
      <p>
       <button type="submit" class="btn btn-primary">Save changes</button>
      </p>
    <% end %>
  </div>
</div>  

app/views/documents/create.js.erb
$(".modal").modal('hide')
$("tbody#container").append("<%= escape_javascript(render :partial => "documents/asset" ,:locals => {:asset => @document}) %>")

app/views/documents/index.html.erb
<%= content_for :head do %>
  <style type="text/css">
    div.content.grid_12 {
      margin :0px;
      
    }
    span.folder_icon {
      background-image: url("/assets/themes/classic/d.png");
      width: 108px;
      height: 72px;
    }

  </style>
  <%= stylesheet_link_tag "/assets/themes/classic/style.css" %>
  <%= javascript_include_tag "/assets/jquery.hotkeys.js" %>
  <%= javascript_include_tag "/assets/jquery.jstree.js" %>
<%end%>
<div class="contour">
  <%= render :partial => "index" ,:locals => {:assets => @assets,:flash => flash ,:parent_id => @parent_id } %>
</div>

<div class="modal" id="modal_container" style="display:none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal" data-cursor="true">×</a>
    <h2 style="color:red;">Error !!!</h2>
  </div>
  <div class="modal-body">
    <p class="error">One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-cursor="true">Close</a>
  </div>
</div>


<!-- TODO write something Better like remote => true for folder instead of the given way -->
<%= javascript_tag  do %>
  $(document).ready(function() {
      $("table#table").delegate("a.folder","click",function(event) {
          event.preventDefault();
          var id = $(this).closest('tr').attr("id");
          $.ajax({
             "url" : $(this).attr("href"),
             "type" : "GET",
             "success" : function(html) {
                $("div.contour").html(html);
                $(".well").jstree("open_node",$("li#"+id));
                $(".well").jstree("select_node",$("li#"+id));
             },
             "error" : function(jqXHR, textStatus, errorThrown) {
                $("div.modal-body").find('p.error').html(textStatus ||  errorThrown);
                $("div#modal_container").modal('show');        
             }
          })
      })
    
      $("div.modal").delegate("a","click",function(event) {
         $("div#modal_container").modal('hide');
      })
      
      $("a[data-cursor=true]").css({"cursor":"pointer"});
      
      $("#fileTree").jstree({
        "json_data"  : {
          "data" : <%= raw folders_structure %> ,
        },
       "themes" : {
          "theme" : "classic",
          "dots" : true,
          "icons" : true
       },
      "plugins" : ["themes",  "json_data" ,"ui"]
     })
      
  })
<%end%>





<%= content_for :sidebar do %>
  <div class="well" id="fileTree">
  </div>
 <%end%>

<%= javascript_tag do %>
  $(document).ready(function() {
    $("#folder_new").bind("ajax:success",function(evt, data, status, xhr) {
       $(".modal").modal('hide');     
    })
    .bind("ajax:error",function(evt, xhr, status, errorThrown) {
      $(".modal").modal('hide');
      $("div.modal-body").find('p.error').html(errorThrown);
      $(".modal#modal_container").modal('show');      
    })

    $("a.clicked").live("click",function(event) {
       
        var id = $(this).attr("data_id");
        $.ajax({
          "url"  :  "/folders/"+id+"/tree_structure",
          "type" : "GET",
          "success" : function(html) {
             $("div.contour").html(html);
          }
        })
        event.preventDefault(); 
    })

   
  })
<%end%>  


 

app/views/documents/new.html.erb
<%= form_for document, :html => {:multipart => true} do |f| %>
  <p>
    <label>Upload Document</label>
    <p>
    <%= f.text_field :name ,:placeholder => "Name of Document" %>
    </p>
    <%= f.file_field :asset %>
    <%= f.hidden_field :asset_cache %>
    <%= f.hidden_field :folder_id ,:value => parent_id %>
  </p>
  <p>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </p>
<% end %>

app/views/documents/show.html.erb
<div class="add-asset" style="float:right">

  <%= link_to 'Download',download_document_path(@document),:class=>"btn addUser" %>
</div>

<h1> Meta data for the document goes here </h1>