config/routes.rb
IitbQuizee::Application.routes.draw do
  

  devise_for :users
   devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
 
 
  resources :users
  
  resources :folders do
    member do
      get 'move'
      get 'tree_structure'
    end

    collection do
      get 'folder_tree'
    end
  end
  
  root :to => "home#index" 
  resources :documents do 
    member do
      get 'download'
    end
  end 
  get "home/dashboard"

end

app/views/layouts/_error.html.erb
<div class="alert alert-block">
  <a class="close">×</a>
  <h4 class="alert-heading"><%= pluralize(object.errors.count, "error") %>:</h4>
  <div class="alert-message">
  <% object.errors.full_messages.each do |msg| %>
    <%= msg %><br /><br />
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IitbQuizee</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <style type="text/css">
    .well {
      min-height: 20px;
      padding: 19px;
      margin-bottom: 20px;
      background-color: whiteSmoke;
      border: 1px solid #EEE;
      border: 1px solid rgba(0, 0, 0, 0.05);
      -webkit-border-radius: 4px;
      -moz-border-radius: 4px;
      border-radius: 4px;
      -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
      -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
    }
  </style>
</head>
<body>
  <div class="container-fluid <%= sidebar_present %> container_16" >
 <!-- Topbar
    ================================================== -->
  <div class="rows-fluid">
    <div class="topbar-wrapper" style="z-index: 5;">
      <div class="topbar" data-dropdown="dropdown" >
        <div class="topbar-inner">
          <div class="container">
            <h3><a href="#">IITB Quizzy</a></h3>
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About Us</a></li>
              <% if current_user %>
                <% if current_user.is_admin? || current_user.is_super_admin? %>
                  <li><a href="<%= users_path%>">User</a></li>
                <% end %>
                  <li><a href="<%= documents_path %>">Document</a></li>
              <% end %>
             </ul>
             <ul class="nav secondary-nav">
             <% if current_user %>
             <li><a>You are login as <span style="font-size:14px;font-weight:bold;color:white;"> <%=current_user.name || current_user.email  %></span></a></li>
              <%else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle">
                  Have an account? <span style="font-size:14px;font-weight:bold;color:white;">Sign in</span>
                </a>
                <ul class="dropdown-menu" id='signin-dropdown'>
                 <%= form_for(resource, :as => resource_name, :url => session_path(resource_name),:html=>{:class=>"login-form"}) do |f| %>
                
                  <div><%= f.label :email %><br />
                  <%= f.email_field :email,:id=>"username" %></div>

                  <div><%= f.label :password %><br />
                  <%= f.password_field :password,:id=>"password" %></div>
                  <div><%= f.submit "Sign in" %></div>
                  <% end %>
                  <li class="divider"></li>
                  <li><a href="#">Another link</a></li>
                </ul>
              </li>
            </ul>
            <% end %>
          </div>
        </div><!-- /topbar-inner -->
      </div><!-- /topbar -->
    </div><!-- /topbar-wrapper -->
    <div class="clear"> </div> 
 </div> 
 
 <div class="rows-fluid" style="top:50px; position:relative;">
   
    <div class="clear"> </div>
    <div class="sidebar <%= sidebar_class %>">
      <%= yield :sidebar %>
    </div>
    <div class="content <%= grid_class %>">
      <%= yield %>
    </div>
  <div class="clear"> </div>
 </div>
</div>
</body>
</html>

app/views/layouts/error.js.erb
$(".modal #error_explanation").html("<%= escape_javascript(render :partial=>"layouts/error",:locals=>{:object=>object})%>")